---
roles:
  pe-puppet-master:
    private_networks:
      - {auto_network: true}
    forwarded_ports:
      - {guest: 443, host: 8443, auto_correct: true}
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024]
    provisioners:
      - type: shell
        inline: "chkconfig iptables off;service iptables stop"
      - type: shell
        inline: "sed -i -e 's|^mirrorlist=|#mirrorlist=|' -e 's|^#baseurl=|baseurl=|' /etc/yum.repos.d/CentOS-Base.repo"
      - {type: hosts, autoconfigure: true, add_localhost_hostnames: false}
      - {type: pe_bootstrap, role: !ruby/sym master}
      - type: shell
        inline: "sed -i -e '/^127/!s|'`hostname -s`'$|'`/opt/puppet/bin/facter fqdn`' '`hostname -s`'|' /etc/hosts"

  pe-puppet-agent:
    private_networks:
      - {auto_network: true}
    provisioners:
#      - type: shell
#        inline: "chkconfig iptables off;service iptables stop;setenforce Permissive;true"
      - type: shell
        inline: "sed -i -e 's|^mirrorlist=|#mirrorlist=|' -e 's|^#baseurl=|baseurl=|' /etc/yum.repos.d/CentOS-Base.repo"
      - {type: hosts, autoconfigure: true, add_localhost_hostnames: false}
      - {type: pe_bootstrap}
      - type: shell
        inline: "sed -i -e '/^127/!s|'`hostname -s`'$|'`/opt/puppet/bin/facter fqdn`' '`hostname -s`'|' /etc/hosts"
